Chapter 5

# Getting Started with Pandas

In [1]:
# Import the modules needed for this chapter.
import numpy as np
import pandas as pd

In [ ]:
# Import most frequently Pandas such as Series and DataFrame
from pandas import Series, DataFrame

## 5.1 Introduction to pandas Data Structures

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Set a random seed to ensure reproducibility of random numbers
np.random.seed(12345)

# Set default figure size for all matplotlib plots
plt.rc("figure", figsize=(10, 6))

# Save the current max rows setting (optional, in case you want to restore it later)
PREVIOUS_MAX_ROWS = pd.options.display.max_rows

# Configure pandas display options for better readability
pd.options.display.max_rows = 20        # Show up to 20 rows when displaying DataFrames
pd.options.display.max_columns = 20     # Show up to 20 columns
pd.options.display.max_colwidth = 80    # Show up to 80 characters per column

# Configure NumPy print options for cleaner numeric output
np.set_printoptions(
    precision=4,   # Display 4 decimal places for floats
    suppress=True  # Suppress scientific notation for small/large numbers
)

### Series

A Series is a one-dimensional array-like object containing a sequence of values (of
similar types to NumPy types) of the same type and an associated array of data labels,
called its index.

In [81]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

You can get the array representation and index object of the Series via
its array and index attributes, respectively:

In [77]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [78]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [80]:
# Create a pandas Series with custom indices
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

# Display the Series
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
# Access the index labels of the Series
obj2.index

In [12]:
obj2["a"]
obj2["d"] = 6
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [86]:
# Access the value associated with index label "a"
obj2["a"]

np.int64(-5)

In [89]:
# Modify the value at index "d" to 6
obj2["d"] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [90]:
# Retrieve multiple values in the order of the specified labels
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [93]:
"b" in obj2

True

In [92]:
"e" in obj2

False

In [95]:
# Define a dictionary with state names as keys and population numbers as values
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

# Create a pandas Series from the dictionary
# The dictionary keys become the index labels, and the values become the data
obj3 = pd.Series(sdata)

# Display the Series
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [98]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [101]:
# Define a list of states, including some not present in the original sdata dictionary
states = ["California", "Ohio", "Oregon", "Texas"]

# Create a new Series using sdata, but restrict/reorder it based on the states list
# For states not found in sdata (e.g., "California"), the value will be NaN (missing)
obj4 = pd.Series(sdata, index=states)

# Display the new Series
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [106]:
# Check for missing (NaN) values in obj4
# Returns a boolean Series: True for missing values, False otherwise
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [107]:
# Check for non-missing (not NaN) values in obj4
# Returns a boolean Series: True where values are present, False where they are missing
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [109]:
# Use the Series method .isna() to check for missing (NaN) values in obj4
# This is equivalent to pd.isna(obj4)
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [110]:
# Display the original Series created from the sdata dictionary
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [111]:
# Display the Series obj4, which uses a custom index (including a state not in sdata)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [112]:
# Add the two Series together
# This performs element-wise addition based on matching index labels
# If a label is missing in either Series, the result will be NaN for that label
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [114]:
# Assign a name to the Series; this is used as the column header when converting to a DataFrame
obj4.name = "population"

# Assign a name to the index; this is useful for labeling the index in tables and plots
obj4.index.name = "state"

# Display the updated Series with named index and values
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### DataFrame

In [116]:
# Define a dictionary with column names as keys and lists of values
# Each list represents a column in the future DataFrame
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],  # State names
    "year": [2000, 2001, 2002, 2001, 2002, 2003],                      # Corresponding years
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]                              # Population figures
}

# Create a DataFrame from the dictionary
# Each key becomes a column; the lists are treated as rows in that column
frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [147]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [148]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [161]:
# Create a DataFrame from the 'data' dictionary
# Specify the order of the columns explicitly using the 'columns' parameter
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [150]:
# Create a new DataFrame from the 'data' dictionary
# Specify column order and include an additional column "debt" that doesn't exist in the original data
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

# Display the resulting DataFrame
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [151]:
# Access the column labels (i.e., the names of all columns) of the DataFrame
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [152]:
# Access the "state" column using dictionary-style indexing (recommended when column names are dynamic or contain spaces)
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [157]:
# Access the "year" column using attribute-style access (works only if the column name is a valid Python identifier)
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [158]:
# Access the row at label/index 1 using label-based indexing with .loc
# This returns a Series representing the row with index label 1
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [159]:
# Access the row at position 2 (third row) using integer-based indexing with .iloc
# This also returns a Series representing the row at that numeric position
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [166]:
# Assign the scalar value 16.5 to every row in the "debt" column
# Since "debt" previously contained NaNs, this replaces them with 16.5
frame2["debt"] = 16.5

# Display the updated DataFrame with all debt values set to 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [167]:
# Replace the "debt" column with an array of 6 values: [0., 1., 2., 3., 4., 5.]
# np.arange(6.) creates a NumPy array of length 6 with float values from 0 to 5
# The array aligns by position with the rows in the DataFrame
frame2["debt"] = np.arange(6.)

# Display the updated DataFrame with the new debt values
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [145]:
# Create a Series named 'val' with custom index labels
# These labels correspond to index values in frame2
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

# Assign the Series 'val' to the "debt" column in frame2
# Pandas aligns values by index label, so only rows with matching index labels ("two", "four", "five")
# will receive values; other rows will get NaN
frame2["debt"] = val

# Display the updated DataFrame
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [168]:
# Create a new column "eastern" in frame2
# This column contains boolean values: True where the "state" is "Ohio", False otherwise
frame2["eastern"] = frame2["state"] == "Ohio"

# Display the updated DataFrame with the new "eastern" column
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   0.0     True
1  2001    Ohio  1.7   1.0     True
2  2002    Ohio  3.6   2.0     True
3  2001  Nevada  2.4   3.0    False
4  2002  Nevada  2.9   4.0    False
5  2003  Nevada  3.2   5.0    False

In [169]:
# Delete the "eastern" column from frame2 (if it exists)
# If "eastern" doesn't exist, this will raise a KeyError
del frame2["eastern"]

# View the current list of column names in frame2 after deletion
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [171]:
# Define a nested dictionary to represent population data
# Outer keys are state names; inner dictionaries map years to population values
populations = {
    "Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
    "Nevada": {2001: 2.4, 2002: 2.9}
}

In [172]:
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [174]:
# Transpose the DataFrame frame3
# This swaps rows and columns: rows become columns and columns become rows
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [176]:
# Create a DataFrame from the nested dictionary 'populations'
# Specify a custom index (row labels): 2001, 2002, 2003
# If a year is not present in the inner dictionary for a state, the value will be NaN
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [177]:
# Create a dictionary 'pdata' by slicing columns from an existing DataFrame 'frame3'
# "Ohio": select all but the last entry (i.e., exclude the last year) from the "Ohio" column
# "Nevada": select the first two entries (i.e., first two years) from the "Nevada" column
pdata = {
    "Ohio": frame3["Ohio"][:-1],
    "Nevada": frame3["Nevada"][:2]
}

# Create a new DataFrame from the sliced data
# Pandas will align the data by index (i.e., year), handling any mismatch with NaN
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [178]:
# Set a name for the row index of frame3
# This is useful for labeling the index axis in outputs like tables or charts
frame3.index.name = "year"

# Set a name for the column index of frame3
# This helps label the columns axis clearly in displays and exports
frame3.columns.name = "state"

# Display the updated DataFrame with named index and columns
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [179]:
# Convert the DataFrame 'frame3' to a NumPy array
# The result is a 2D array containing only the data values (no row/column labels)
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [180]:
# Convert the DataFrame 'frame2' to a NumPy array
# This returns a 2D array of the underlying data without row or column labels
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, 0.0],
       [2001, 'Ohio', 1.7, 1.0],
       [2002, 'Ohio', 3.6, 2.0],
       [2001, 'Nevada', 2.4, 3.0],
       [2002, 'Nevada', 2.9, 4.0],
       [2003, 'Nevada', 3.2, 5.0]], dtype=object)

### Index Objects

In [182]:
# Create a Series with values [0, 1, 2] and custom index labels ['a', 'b', 'c']
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

# Get the index object from the Series
# This is a pandas Index object containing ['a', 'b', 'c']
index = obj.index

# Display the full index
index

# Slice the index from position 1 onward (i.e., get ['b', 'c'])
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
# Create a pandas Index object with values [0, 1, 2]
labels = pd.Index(np.arange(3))

# Display the Index object
labels

Index([0, 1, 2], dtype='int64')

In [185]:
# Create a Series with custom index 'labels'
# Values are [1.5, -2.5, 0] and indices are [0, 1, 2] from 'labels'
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

# Display the Series
obj2

# Check whether the index of obj2 is the *same object* as 'labels' (not just equal, but identical)
obj2.index is labels

True

In [186]:
# Display the DataFrame 'frame3'
frame3

# Access the column labels of 'frame3'
# This returns a pandas Index object listing the state names (e.g., 'Ohio', 'Nevada')
frame3.columns

# Check if the column label 'Ohio' exists in frame3
# Returns True if 'Ohio' is one of the columns
"Ohio" in frame3.columns

# Check if the index label 2003 exists in frame3
# Returns True if 2003 is one of the row index labels (e.g., a year)
2003 in frame3.index

False

In [188]:
# Create a pandas Index object with duplicate labels
# Index labels: ['foo', 'foo', 'bar', 'bar']
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 Essential Functionality

### Reindexing

In [210]:
# Create a pandas Series with values [4.5, 7.2, -5.3, 3.6]
# Assign custom index labels ["d", "b", "a", "c"] to these values
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

# Display the Series
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [211]:
# Reindex the Series 'obj' to include a new set of index labels: ["a", "b", "c", "d", "e"]
# This reorders existing entries and introduces a new label "e", which will have a NaN value
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

# Display the resulting Series
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [212]:
# Create a Series with string values and a non-continuous integer index
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

# Display the Series
obj3

0      blue
2    purple
4    yellow
dtype: object

In [213]:
# Reindex obj3 to include a full range of indices from 0 to 5
# Use forward-fill ('ffill') to propagate the last valid value forward into missing entries
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
# Create a 3x3 DataFrame with values from 0 to 8, reshaped as a 3-row matrix
# Assign custom row index labels: ["a", "c", "d"]
# Assign column names: ["Ohio", "Texas", "California"]
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])

# Display the original DataFrame
frame

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [214]:
# Reindex the DataFrame to include a new row label "b"
# Existing rows are retained, and "b" is added with NaNs for all columns (since no data existed for it)
frame2 = frame.reindex(index=["a", "b", "c", "d"])

# Display the reindexed DataFrame
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [200]:
# Define a list of column names to reindex the DataFrame's columns
# Includes one column ("Utah") that doesn't exist in the original DataFrame
states = ["Texas", "Utah", "California"]

# Reindex the DataFrame 'frame' to include only the specified columns, in the given order
# Columns not present in the original (like "Utah") will be filled with NaN
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [201]:
# Reindex the columns of 'frame' using the list 'states'
# Equivalent to frame.reindex(columns=states), just a different syntax
# axis="columns" (or axis=1) specifies you're reindexing the columns, not the rows
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [202]:
# Use .loc to select specific rows and columns from the DataFrame 'frame'
# Row labels: ["a", "d", "c"]
# Column labels: ["California", "Texas"]
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

### Dropping Entries from an Axis

In [54]:
# Create a Series with float values from 0.0 to 4.0
# Assign custom index labels: ["a", "b", "c", "d", "e"]
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

# Display the original Series
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [206]:
# Drop the entry with label "c" from the Series and store the result in a new Series
# This returns a new Series without "c"; the original 'obj' remains unchanged
new_obj = obj.drop("c")

# Display the new Series without "c"
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [207]:
# Drop multiple entries with labels "d" and "c" from the original Series
# Again, this returns a new Series without those two labels
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [208]:
# Create a 4x4 DataFrame with values from 0 to 15
# Reshape it into 4 rows and 4 columns
# Set custom row labels (index): ["Ohio", "Colorado", "Utah", "New York"]
# Set custom column names: ["one", "two", "three", "four"]
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

# Display the resulting DataFrame
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [209]:
# Drop rows with index labels "Colorado" and "Ohio" from the DataFrame 'data'
# Returns a new DataFrame without those two rows
# The original 'data' remains unchanged unless assigned or modified with inplace=True
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [215]:
# Drop the column named "two" from the DataFrame 'data'
# Returns a new DataFrame without the "two" column
# The original 'data' is unchanged unless modified with inplace=True
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [217]:
# Drop the column named "two" using axis=1 (which refers to columns)
# Same as: data.drop(columns=["two"])
# Returns a new DataFrame without the "two" column
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [218]:
# Drop multiple columns ("two" and "four") using axis="columns" (equivalent to axis=1)
# Returns a new DataFrame without the specified columns
data.drop(["two", "four"], axis="columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [221]:
# Create a Series with float values from 0.0 to 3.0
# Custom index labels: ["a", "b", "c", "d"]
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

# Display the full Series
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [222]:
# Access the value associated with label "b"
obj["b"]

np.float64(1.0)

In [223]:
# Access the value at position 1 (which is label "b")
obj[1]

/var/folders/39/dfgrl3qn3h96qwn73dszww2c0000gq/T/ipykernel_2134/1620370958.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [225]:
# Slice values from index positions 2 to 3 (excludes 4), i.e., labels "c" and "d"
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [ ]:
# Access multiple elements by label, in the given order: "b", "a", "d"
obj[["b", "a", "d"]]

In [227]:

# Access multiple elements by position (integer index): positions 1 and 3 (i.e., "b" and "d")
obj[[1, 3]]

/var/folders/39/dfgrl3qn3h96qwn73dszww2c0000gq/T/ipykernel_2134/4280588667.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [228]:
# Boolean filtering: return elements less than 2.0
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [230]:
# Use .loc to select multiple elements by their **labels** in a specific order
# This is label-based indexing; useful when you want to retrieve data by index name
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [231]:
# Create a Series with values [1, 2, 3] and custom integer index labels [2, 0, 1]
# The order of the indices is out of the usual sequence
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

# Create another Series with the same values but using string index labels ["a", "b", "c"]
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [232]:
print(obj1)
print(obj2)

2    1
0    2
1    3
dtype: int64
a    1
b    2
c    3
dtype: int64

In [233]:
# For obj1, the index labels are [2, 0, 1]
# When you do obj1[[0, 1, 2]], you're selecting by **label**, not position
# So this tries to retrieve index labels 0, 1, and 2 — which all exist
obj1[[0, 1, 2]]  # Returns values in label order: 0 → 1 → 2

0    2
1    3
2    1
dtype: int64

In [234]:
# For obj2, the index labels are ["a", "b", "c"]
# obj2[[0, 1, 2]] will raise a KeyError, because labels 0, 1, and 2 do not exist
# It is trying to access labels 0, 1, 2 — not positions
obj2[[0, 1, 2]]  # ❌ KeyError

/var/folders/39/dfgrl3qn3h96qwn73dszww2c0000gq/T/ipykernel_2134/2435728440.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]  # ❌ KeyError

a    1
b    2
c    3
dtype: int64

In [235]:
# Use .loc to perform **label-based slicing** from "b" to "c" (inclusive)
# Since Series index is ["a", "b", "c"], this returns elements with labels "b" and "c"
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [236]:
# Set the values of the index labels from "b" to "c" (inclusive) to 5
# Since obj2 has index ["a", "b", "c"], this will update both "b" and "c"
obj2.loc["b":"c"] = 5

# Display the modified Series
obj2

a    1
b    5
c    5
dtype: int64

In [237]:
# Create a 4x4 DataFrame with values from 0 to 15 reshaped into 4 rows and 4 columns
# Rows are labeled by state names, and columns are ["one", "two", "three", "four"]
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

# Display the full DataFrame
data

# Access the column named "two" — returns a Series with values from that column
data["two"]

# Access multiple columns: "three" and "one" (in that specific order)
# This returns a new DataFrame with only those two columns
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [238]:
# Select the first two rows of the DataFrame using slicing
# This is position-based row slicing (like standard Python slicing)
data[:2]

# Filter rows where the value in the "three" column is greater than 5
# Returns a DataFrame with only the rows that satisfy the condition
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [239]:
# Perform an element-wise comparison of all values in the DataFrame with 5
# Returns a DataFrame of the same shape containing Boolean values:
# True where the original value is less than 5, False otherwise
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [240]:
# Replace all values in the DataFrame that are less than 5 with 0
# This is done using a Boolean mask (data < 5), and assignment
data[data < 5] = 0

# Display the updated DataFrame
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection on DataFrame with loc and iloc

In [244]:
# Access the row labeled "Colorado" using .loc
# This returns a Series containing all columns for the "Colorado" row
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [245]:
# Select multiple rows by their index labels using .loc
# Pass a list of labels: ["Colorado", "New York"]
# Returns a new DataFrame with just those two rows
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [246]:
# Select specific columns from a specific row using .loc
# First argument is the row label: "Colorado"
# Second argument is a list of column labels: ["two", "three"]
# Returns a Series with the selected values from that row and columns
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [247]:
# Select the row at index position 2 (third row in the DataFrame)
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [248]:
# Select rows at index positions 2 and 1 (i.e., third and second rows)
# Returns a DataFrame with those two rows
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [249]:
# Select values from row index 2 (third row),
# and only from columns at positions 3, 0, and 1 (i.e., "four", "one", "two")
# Returns a Series of selected values
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [250]:
# Select rows at index positions 1 and 2 (second and third rows),
# and columns at positions 3, 0, and 1 (i.e., "four", "one", "two")
# Returns a DataFrame with the specified subset
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [251]:
# Select rows from the beginning up to and including the row labeled "Utah"
# Then select only the "two" column
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [252]:
# First, select all rows and the first 3 columns using iloc (i.e., "one", "two", "three")
# Then, filter rows where the value in the "three" column is greater than 5
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [253]:
# Filter rows in the DataFrame where the value in the "three" column is greater than or equal to 2
# This uses boolean indexing with .loc for label-based selection
data.loc[data.three >= 2]

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Integer indexing pitfalls

In [ ]:
# Create a Series with 3 float values: 0.0, 1.0, 2.0
# The index will be the default: 0, 1, 2
ser = pd.Series(np.arange(3.))

In [254]:
# Attempt to access the last element using negative indexing
# WARNING: This will raise a KeyError in pandas if the index does not include -1
ser[-1]  # ❌ This raises a KeyError unless -1 is an actual index label

KeyError: -1

In [255]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [256]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])
ser2[-1]

/var/folders/39/dfgrl3qn3h96qwn73dszww2c0000gq/T/ipykernel_2134/821879068.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]

np.float64(2.0)

In [257]:
# Access the last element in the Series using position-based indexing
ser.iloc[-1]

np.float64(2.0)

In [258]:
# Slice the Series from the beginning up to (but not including) index position 2
ser[:2]

0    0.0
1    1.0
dtype: float64

#### Pitfalls with chained indexing

In [268]:
# Overwrite the entire "one" column with the value 1
data.loc[:, "one"] = 1
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        1    5      5     5
New York    1    3      3     3

In [269]:
# Overwrite the entire row at index position 2 (i.e., the third row) with the value 5
data.iloc[2] = 5
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      5     5
New York    1    3      3     3

In [276]:
# For rows where the value in the "four" column is greater than 5,
# set *all columns* in those rows to the value 3
data.loc[data["four"] > 5] = 3
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      6     5
New York    1    3      3     3

In [277]:
data.loc[data.three == 5]["three"] = 6
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      6     5
New York    1    3      3     3

In [272]:
# Find rows where the value in the "three" column is equal to 5,
# and update only those "three" values to 6
data.loc[data.three == 5, "three"] = 6
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      6     5
New York    1    3      3     3

### Arithmetic and Data Alignment

In [273]:
# Create a Series s1 with custom index labels
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

# Create another Series s2 with overlapping and non-overlapping index labels
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [285]:
# Add two Series s1 and s2 together
result = s1 + s2

In [288]:
# Create first DataFrame df1 with shape (3, 3)
# Columns are 'b', 'c', 'd' and rows are labeled with state names
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])

# Create second DataFrame df2 with shape (4, 3)
# Columns are 'b', 'd', 'e' and rows are also labeled with state names
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])

In [287]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [289]:
# Create first DataFrame with a single column "A"
df1 = pd.DataFrame({"A": [1, 2]})

# Create second DataFrame with a different single column "B"
df2 = pd.DataFrame({"B": [3, 4]})

# Display both DataFrames
df1
df2

# Attempt to add df1 and df2
df1 + df2

    A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [290]:
# Create df1: a 3x4 DataFrame with columns 'a', 'b', 'c', 'd'
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))

# Create df2: a 4x5 DataFrame with columns 'a', 'b', 'c', 'd', 'e'
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))

# Set the value in row index 1, column 'b' of df2 to NaN (missing value)
df2.loc[1, "b"] = np.nan

# Display df1
df1

# Display df2
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [295]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [292]:
# Perform element-wise addition between df1 and df2
# For any missing (non-overlapping) values, treat them as 0 instead of NaN
result = df1.add(df2, fill_value=0)
result

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [294]:
# Element-wise reciprocal of df1
1 / df1
# Equivalent operation using the reverse division method
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [293]:
# Reindex df1 to match the column labels of df2
# For any new columns (not in df1), fill the values with 0
df1_aligned = df1.reindex(columns=df2.columns, fill_value=0)

#### Operations between DataFrame and Series

In [296]:
# Create a 3x4 NumPy array with values from 0 to 11
arr = np.arange(12.).reshape((3, 4))

# View the entire array
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [297]:
# Access the first row of the array
arr[0]

array([0., 1., 2., 3.])

In [300]:
# Subtract the first row from all rows using broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [301]:
# Create a 4x3 DataFrame with values from 0 to 11
# Rows are labeled by states; columns are labeled 'b', 'd', 'e'
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])

# Display the DataFrame
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [303]:
series = frame.iloc[0]

In [306]:
# Subtract the first row (Utah) from every row in the DataFrame
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [311]:
# Create a Series with index labels that partially overlap with the DataFrame's columns
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

# Display the Series
series2

b    0
e    1
f    2
dtype: int64

In [310]:
# Add the Series to the DataFrame
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [ ]:
# Extract the "d" column from the DataFrame `frame` and store it as a Series
series3 = frame["d"]

# Display the original DataFrame
frame

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [314]:
# Display the extracted Series (column "d")
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [315]:
# Subtract `series3` (which has the same index as `frame`) from each row of `frame`
# The subtraction is aligned along the row index (axis="index")
frame.sub(series3, axis="index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [ ]:
# Create a 4x3 DataFrame `frame` filled with random values 
# drawn from a standard normal distribution (mean=0, std=1)
# Columns are labeled "b", "d", and "e"
# Rows are labeled by state names
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])

# Display the randomly generated DataFrame
frame

In [ ]:
# Apply the absolute value function to each element in the DataFrame
# This converts all negative values to positive
np.abs(frame)

In [316]:
# Define a function that computes the range (max - min) of a Series
# This function will be applied to each column (by default) of the DataFrame
def f1(x):
    return x.max() - x.min()

# Apply the function `f1` to each column of the DataFrame `frame`
# This returns a Series containing the range for each column
frame.apply(f1)

b    9.0
d    9.0
e    9.0
dtype: float64

In [ ]:
# Apply the custom function `f1` to each row of the DataFrame
# `f1` computes the difference between the max and min of a Series
# Setting axis="columns" applies the function across columns (i.e., row-wise)
frame.apply(f1, axis="columns")

In [317]:
# Define a function that returns the min and max of a Series as a new Series
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

# Apply the function `f2` to each column of the DataFrame (default axis=0)
# This returns a DataFrame where each column contains the min and max values of the original columns
frame.apply(f2)

       b     d     e
min  0.0   1.0   2.0
max  9.0  10.0  11.0

In [319]:
# Define a formatting function that takes a numeric value and returns a string
# formatted to 2 decimal places
def my_format(x):
    return f"{x:.2f}"

# Apply the formatting function elementwise to each value in the DataFrame
# using applymap (used for element-wise operations on DataFrames)
frame.applymap(my_format)

/var/folders/39/dfgrl3qn3h96qwn73dszww2c0000gq/T/ipykernel_2134/2736939494.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)

           b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [320]:
# Apply the 'my_format' function to each element in the 'e' column of the DataFrame.
# The 'map' method is used for element-wise operations on Series.
frame["e"].map(my_format)

Utah       2.00
Ohio       5.00
Texas      8.00
Oregon    11.00
Name: e, dtype: object

### Sorting and Ranking

In [321]:
# Create a pandas Series with custom index labels
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

# Display the original Series (unsorted by index)
obj

d    0
a    1
b    2
c    3
dtype: int64

In [322]:
# Sort the Series by its index labels in alphabetical order
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [323]:
# Create a DataFrame with shape (2 rows x 4 columns)
# The data comes from np.arange(8), reshaped into 2 rows and 4 columns
# Rows are labeled "three" and "one", and columns are labeled "d", "a", "b", "c"
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])

# Display the original DataFrame
frame

# Sort the DataFrame by index (row labels) in ascending order
frame.sort_index()

# Sort the DataFrame by column labels in ascending order
frame.sort_index(axis="columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [324]:
# Sort the DataFrame by column labels in **descending** alphabetical order
# axis="columns" means we're sorting the column names, not the row index
# ascending=False ensures the sort is from Z to A
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [325]:
# Create a pandas Series with default integer indices (0 to 3)
obj = pd.Series([4, 7, -3, 2])

# Sort the Series values in ascending order (by default)
# The result will show values sorted but retain their original indices
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [326]:
# Create a pandas Series containing some numeric values and NaNs
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

# Sort the Series values in ascending order
# NaN values are placed at the end by default
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [327]:
# Sort the Series values in ascending order
# Place NaN values at the beginning instead of the default (end)
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [328]:
# Create a DataFrame with two columns: 'b' and 'a'
frame = pd.DataFrame({
    "b": [4, 7, -3, 2],  # Numerical values for column 'b'
    "a": [0, 1, 0, 1]    # Binary values for column 'a'
})

# Display the DataFrame
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [329]:
# Sort the DataFrame by the values in column 'b' in ascending order
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [331]:
# Sort the DataFrame first by column 'a', then by column 'b' (both in ascending order by default)
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [332]:
# Create a Series with some duplicate values
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

# Rank the values in the Series
# By default, method="average" assigns the average rank to tied elements
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [333]:
# Rank the values in the Series using the "first" method
# The "first" method assigns ranks in the order the values appear, without averaging for ties
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [334]:
# Rank the values in descending order (highest value gets rank 1)
# Tied values will receive the average of the ranks they span
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [335]:
# Create a DataFrame with three columns: 'b', 'a', and 'c'
frame = pd.DataFrame({
    "b": [4.3, 7, -3, 2],
    "a": [0, 1, 0, 1],
    "c": [-2, 5, 8, -2.5]
})

# Display the DataFrame
frame

# Compute the rank **across columns** (i.e., horizontally for each row)
# Lower values get lower ranks (1 = smallest in the row)
frame.rank(axis="columns")

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [336]:
# Create a pandas Series with duplicate indices
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

# Display the Series
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [337]:
# Check if the index has all unique labels (returns False because 'a' and 'b' appear twice)
obj.index.is_unique

False

In [338]:
# Access all values corresponding to index label "a"
# Since "a" appears more than once in the index, this returns a Series
obj["a"]

a    0
a    1
dtype: int64

In [339]:
# Access the value corresponding to index label "c"
# Since "c" is unique, this returns a scalar (a single value)
obj["c"]

np.int64(4)

In [341]:
# Create a DataFrame with random standard normal values, 5 rows × 3 columns
# The index contains duplicate labels: "a" and "b" each appear twice
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a", "b", "b", "c"])

# Display the entire DataFrame
df

          0         1         2
a  0.886429 -2.001637 -0.371843
a  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228
b -0.577087  0.124121  0.302614
c  0.523772  0.000940  1.343810

In [343]:
# Select all rows with index label "b"
# Since "b" appears twice, this returns a DataFrame with 2 rows
df.loc["b"]

          0         1         2
b  0.476985  3.248944 -1.021228
b -0.577087  0.124121  0.302614

In [342]:
# Select the row with index label "c"
# Since "c" appears once, this returns a Series
df.loc["c"]

0    0.523772
1    0.000940
2    1.343810
Name: c, dtype: float64

## 5.3 Summarizing and Computing Descriptive Statistics

In [345]:
# Create a DataFrame with some missing (NaN) values
df = pd.DataFrame([[1.4, np.nan],      # Row 'a': one valid, one NaN
                   [7.1, -4.5],        # Row 'b': both valid
                   [np.nan, np.nan],   # Row 'c': both missing
                   [0.75, -1.3]],      # Row 'd': both valid
                  index=["a", "b", "c", "d"],     # Custom row labels
                  columns=["one", "two"])         # Column names

# Display the DataFrame
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [346]:
# Sum the values in each column, ignoring NaN by default
df.sum()

one    9.25
two   -5.80
dtype: float64

In [347]:
# Sum the values in each row (across columns), ignoring NaN by default
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [348]:
# Sum the values in each column, treating NaN as-is (result will be NaN if any NaN is present in a column)
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [349]:
# Sum the values in each row, treating NaN as-is (result will be NaN if any NaN is present in a row)
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [350]:
# Compute the mean of each row, skipping NaN by default
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [351]:
# Return the index (row label) of the first occurrence of the maximum value for each column
df.idxmax()

one    b
two    d
dtype: object

In [ ]:
# Compute the cumulative sum of each column (ignoring NaNs by default)
df.cumsum()

In [ ]:
# Generate descriptive statistics for each column in the DataFrame
df.describe()

In [352]:
# Generate descriptive statistics for a Series of string values
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [353]:
# Load the 'price' DataFrame from a pickle file containing stock price data
price = pd.read_pickle("examples/yahoo_price.pkl")

# Load the 'volume' DataFrame from a pickle file containing stock trading volume data
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [354]:
# Compute percentage change between current and prior elements for each stock
returns = price.pct_change()

# Display the last 5 rows of the resulting returns DataFrame
returns.tail()

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [355]:
# Compute the Pearson correlation between MSFT and IBM daily returns
returns["MSFT"].corr(returns["IBM"])

# Compute the covariance between MSFT and IBM daily returns
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703552e-05)

In [356]:
# Compute the pairwise correlation matrix between all stock return series
returns.corr()

# Compute the pairwise covariance matrix between all stock return series
returns.cov()

          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [357]:
# Compute pairwise correlations between each column in `returns` and the 'IBM' column
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [358]:
# Compute pairwise correlations between each column in `returns` and the corresponding column in `volume`
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

### Unique Values, Value Counts, and Membership

In [360]:
# Create a pandas Series with some repeated string values
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [361]:
# Get the unique values in the Series
uniques = obj.unique()
uniques  # Output: array of unique elements from the Series

array(['c', 'a', 'd', 'b'], dtype=object)

In [362]:
# Count the frequency of each unique value in the Series
obj.value_counts()
# Output: Series showing unique values as index and their counts as values, sorted in descending order

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [363]:
# Count unique values in the Series after converting to a NumPy array,
# without sorting the result
pd.value_counts(obj.to_numpy(), sort=False)
# Output: Series showing counts of each unique value in the original order of appearance

/var/folders/39/dfgrl3qn3h96qwn73dszww2c0000gq/T/ipykernel_2134/199629044.py:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [364]:
obj
# Displays the original Series

mask = obj.isin(["b", "c"])
# Creates a boolean mask identifying elements that are either 'b' or 'c'

mask
# Displays the boolean mask

obj[mask]
# Filters the Series using the mask to show only the elements that are 'b' or 'c'

0    c
5    b
6    b
7    c
8    c
dtype: object

In [365]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
# Series of values that we want to match against unique values

unique_vals = pd.Series(["c", "b", "a"])
# Series of unique values to match from

indices = pd.Index(unique_vals).get_indexer(to_match)
# Uses get_indexer to find the indices of each element in to_match within unique_vals
# Returns -1 if an element in to_match is not found in unique_vals

indices
# Displays the resulting index positions for each element in to_match

array([0, 2, 1, 1, 0, 2])

In [366]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
# Creates a DataFrame with three columns: 'Qu1', 'Qu2', and 'Qu3', each containing five numeric values

data
# Displays the DataFrame

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [ ]:
data["Qu1"].value_counts().sort_index()
# Counts the frequency of each unique value in the 'Qu1' column
# Then sorts the result by index (i.e., the unique values themselves)

In [367]:
result = data.apply(pd.value_counts).fillna(0)
# Applies 'value_counts' to each column in the DataFrame
# Produces a DataFrame where the index is the unique values across all columns
# and the columns are the original columns with counts
# Missing values (NaN) are replaced with 0 for uniformity

/var/folders/39/dfgrl3qn3h96qwn73dszww2c0000gq/T/ipykernel_2134/1671435560.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)

In [ ]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
# Creates a DataFrame with two columns 'a' and 'b'

data.value_counts()
# Counts the number of unique rows (combinations of values across columns)
# Returns a Series with row combinations as index and their counts as values

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS
# Restores the previous setting for the maximum number of rows displayed in pandas output
# Useful if you previously changed it to display more or fewer rows